# Generated by Django 4.2.4 on 2023-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccounts',
            name='account_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
